# Generated by Django 3.2.8 on 2021-11-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('administrador', models.CharField(max_length=50, verbose_name='administrador')),
                ('telefono', models.CharField(max_length=50, verbose_name='telefono')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('ciudad', models.CharField(max_length=80, unique=True, verbose_name='ciudad')),
            ],
        ),
    ]
