# Generated by Django 3.2.8 on 2021-11-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='ciudad',
            field=models.CharField(max_length=80, verbose_name='ciudad'),
        ),
    ]
